### ISSUE TITLE
Class instantion error on jdk15

### ISSUE THREAD

**Issue by rudivk** [markenwerk/java-utils-mail-dkim#29]
Hi,

I have been using your library happily for the last year and I am currently in the process of upgrading to jdk 15 and I am having the following issue:

`
com.linkedstrategies.infinity.mailserver.UncheckedMessagingException: net.markenwerk.utils.mail.dkim.DkimSigningException: Obtaining the domain key for infinityappointments.com.infinity failed;
  nested exception is:
        java.io.IOException: net.markenwerk.utils.mail.dkim.DkimException: Selector lookup failed
        at com.linkedstrategies.infinity.mailserver.impl.OutgoingMailProcessor$MailMessage.send(OutgoingMailProcessor.java:626)
        at com.linkedstrategies.infinity.mailserver.impl.OutgoingMailProcessor$InitialAttemptProcessor.send(OutgoingMailProcessor.java:316)
        at com.linkedstrategies.infinity.mailserver.impl.OutgoingMailProcessor$InitialAttemptProcessor.process(OutgoingMailProcessor.java:282)
        at com.linkedstrategies.infinity.mailserver.impl.OutgoingMailProcessor$InitialAttemptProcessor.process(OutgoingMailProcessor.java:273)
        at com.linkedstrategies.infinity.infrastructure.jms.TextMessageProcessor.process(TextMessageProcessor.java:57)
        at com.linkedstrategies.infinity.infrastructure.jms.impl.ConsumerThread.doProcess(ConsumerThread.java:152)
        at com.linkedstrategies.infinity.infrastructure.jms.impl.ConsumerThread.runWhileActive(ConsumerThread.java:104)
        at com.linkedstrategies.infinity.infrastructure.jms.impl.ConsumerThread.run(ConsumerThread.java:68)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: net.markenwerk.utils.mail.dkim.DkimSigningException: Obtaining the domain key for infinityappointments.com.infinity failed;
  nested exception is:
        java.io.IOException: net.markenwerk.utils.mail.dkim.DkimException: Selector lookup failed
        at net.markenwerk.utils.mail.dkim.DkimSigner.sign(DkimSigner.java:424)
        at net.markenwerk.utils.mail.dkim.DkimMessage.writeTo(DkimMessage.java:116)
        at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1315)
        at javax.mail.Transport.send0(Transport.java:255)
        at javax.mail.Transport.send(Transport.java:124)
        at com.linkedstrategies.infinity.mailserver.impl.OutgoingMailProcessor$MailMessage.sendTo(OutgoingMailProcessor.java:701)
        at com.linkedstrategies.infinity.mailserver.impl.OutgoingMailProcessor$MailMessage.send(OutgoingMailProcessor.java:591)
        ... 10 more
Caused by: java.io.IOException: net.markenwerk.utils.mail.dkim.DkimException: Selector lookup failed
        at net.markenwerk.utils.mail.dkim.DkimSigningException.<init>(DkimSigningException.java:69)
        ... 17 more
Caused by: net.markenwerk.utils.mail.dkim.DkimException: Selector lookup failed
        at net.markenwerk.utils.mail.dkim.DomainKeyUtil.getValue(DomainKeyUtil.java:214)
        at net.markenwerk.utils.mail.dkim.DomainKeyUtil.getTags(DomainKeyUtil.java:127)
        at net.markenwerk.utils.mail.dkim.DomainKeyUtil.fetchDomainKey(DomainKeyUtil.java:106)
        at net.markenwerk.utils.mail.dkim.DomainKeyUtil.getDomainKey(DomainKeyUtil.java:100)
        at net.markenwerk.utils.mail.dkim.DomainKeyUtil.getDomainKey(DomainKeyUtil.java:90)
        at net.markenwerk.utils.mail.dkim.DkimSigner.sign(DkimSigner.java:422)
        ... 16 more
Caused by: javax.naming.NoInitialContextException: Cannot instantiate class: com.sun.jndi.dns.DnsContextFactory [Root exception is java.lang.IllegalAccessException: class javax.naming.spi.NamingManager (in module java.naming) cannot access class com.sun.jndi.dns.DnsContextFactory (in module jdk.naming.dns) because module jdk.naming.dns does not export com.sun.jndi.dns to module java.naming]
        at java.naming/javax.naming.spi.NamingManager.getFactory(NamingManager.java:749)
        at java.naming/javax.naming.spi.NamingManager.lambda$getInitialContext$1(NamingManager.java:711)
        at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329)
        at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205)
        at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:711)
        at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
        at java.naming/javax.naming.InitialContext.init(InitialContext.java:236)
        at java.naming/javax.naming.InitialContext.<init>(InitialContext.java:208)
        at java.naming/javax.naming.directory.InitialDirContext.<init>(InitialDirContext.java:130)
        at net.markenwerk.utils.mail.dkim.DomainKeyUtil.getValue(DomainKeyUtil.java:193)
        ... 21 more
Caused by: java.lang.IllegalAccessException: class javax.naming.spi.NamingManager (in module java.naming) cannot access class com.sun.jndi.dns.DnsContextFactory (in module jdk.naming.dns) because module jdk.naming.dns does not export com.sun.jndi.dns to module java.naming
        at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:385)
        at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:693)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:490)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:350)
        at java.base/java.lang.Class.newInstance(Class.java:645)
        at java.naming/javax.naming.spi.NamingManager.getFactory(NamingManager.java:746)
        ... 30 more
`

There was a similar issue in jdk9 (https://bugs.openjdk.java.net/browse/JDK-8186019) but that has been fixed long ago. Thinking that maybe this is a regression bug, I wrote a little main that also creates an InitialDirContext using jdk15 and it runs just fine so this is not a regression issue I think. The example main class is below:
`public static void main(String[] args) {
        Properties env = new Properties();
        env.put(Context.INITIAL_CONTEXT_FACTORY, "com.sun.jndi.dns.DnsContextFactory");
        try {
            InitialDirContext initialDirContext = new InitialDirContext(env);
            Attributes attrs = initialDirContext.getAttributes("gmail.com", MX_ATTRIBS);
            Attribute attr = attrs.get(MX_ATTRIB);
            Set<String> hostNames = new HashSet<>();
            if (attr != null) {
                for (int i = 0; i < attr.size(); i++) {
                    String mxAttr = (String) attr.get(i);
                    String[] parts = mxAttr.split(" ");
                    hostNames.add(parts[1].substring(0, parts[1].length() - 1));
                }
            }
            System.out.println("hostNames = " + hostNames.stream().sorted().collect(Collectors.joining(", ")));
        } catch (NamingException e) {
            e.printStackTrace(System.err);
        }
    }`

Could this be related to the 1.7 that you are building against? In other words, do you think it's worthwhile to just take your source code and drop it into my project and recompile them against 1.5 and see how that goes?

**Comment by rudivk** [comment]
I have incorporated your source code into my code base and it works just fine now.
